[package]
name = "there_are_no_executables"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url = "2.3.1"
byteorder = "1.4.3"
ntapi = "0.4.0"

[dependencies.windows]
version = "0.42.0"
features = [
    "Win32_Security",
    "Win32_Foundation",
    "Win32_System_Memory",    
    "Win32_System_Threading",  
    "Win32_Storage_FileSystem",
    "Win32_System_LibraryLoader",
    "Win32_Networking_WinHttp", 
    "Win32_System_WindowsProgramming", 
    "Win32_System_SystemServices",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_SystemInformation",
    "Win32_UI_WindowsAndMessaging"
]